# scripts section
[scripts]
#[scripts.oncreate]
## universal = {}
## linux = {}
## macos = {}
## windows = {}
[scripts.onmount]
[scripts.onmount.universal]
init_package = [
    "go mod init {{ .ModuleName }}",
    "go mod tidy"
]
init_git = ["git init"]
